workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.emirdeliz.myfirstwords"
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.configureondemand=true"
    scripts:
      - name: Set up environment
        script: |
          flutter --version
          java -version
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
